image: elavram/ubuntu:latest

stages:
  - build
  - test

build:ubuntu:
  stage: build
  tags:
    - docker
  script:
    - apt install -qq -y libhdf5-dev
    - cd /builds/$CI_PROJECT_PATH
    - mkdir build
    - cd build
    - cmake -DSTATIONSIM_ENABLE_OPENMP=OFF -DSTATIONSIM_ENABLE_MPI=OFF ..
    - make
  artifacts:
    paths:
      - build