name: CI

on:
  push:
    branches: "master"
    tags: ["*"]
  pull_request:
  release:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get install python3-numpy python3-matplotlib openmpi-bin libopenmpi-dev libhdf5-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DSTATIONSIM_ENABLE_OPENMP=OFF ..
      - name: Run tests
        run: ctest
